version: "2.1"
services:
  db:
    image: mysql:5.5
    container_name: splay_db
    environment:
      MYSQL_ROOT_PASSWORD: "splay"
      MYSQL_DATABASE: "splay"
      MYSQL_USER: "splay"
      MYSQL_PASSWORD: "splay"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 100
    ports:
      - "3306:3306"
  controller:
    build:
      context: ./src/controller
    container_name: splay_controller
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /tmp/splaylogs/logs:/usr/splay/logs
  daemon:
    build:
      context: ./src/daemon
    depends_on: ["controller"]
  cli_server:
    build:
      context: ./src/
      dockerfile: cli_server/Dockerfile
    container_name: splay_cli_server
    ports: ["2222:2222"]
    depends_on: ["controller"]
    volumes:
      - /tmp/splaylogs/logs:/usr/splay/logs
  cli_client:
    build:
      context: ./src/cli_client
    container_name: splay_cli_client
    depends_on: ["cli_server"]
  splayweb:
    build:
      context: ./src/splayweb
      dockerfile: Dockerfile
    container_name: splayweb
    ports:
      - "80:80"
    depends_on: ["controller"]
    command: bundle exec rails s -p 80 -b '0.0.0.0'

