version: "2.1"
services:
  db:
    image: mysql:5.5
    container_name: splay_db
    environment:
      MYSQL_ROOT_PASSWORD: "splay"
      MYSQL_DATABASE: "splay"
      MYSQL_USER: "splay"
      MYSQL_PASSWORD: "splay"
  controller:
    build:
      context: ./src/controller
      dockerfile: controller.dockerfile
    container_name: splay_controller
    depends_on: ["db"]
    command: ["./deploy_controller.sh"]
  daemon:
    build:
      context: ./src/daemon
    depends_on: ["controller"]
  web_server:
    build:
      context: ./src/controller
      dockerfile: web_server.dockerfile
    container_name: splay_web_server
    ports: ["2222:2222"]
    depends_on: ["controller"]
    command: ["./deploy_web_server.sh"]
  terminal:
    build:
      context: ./src/rpc_client
    container_name: splay_terminal
    depends_on: ["web_server"]
