version: "2.2"
services:
  # IMAGE : MySql database - the first to be launch
  db:
    image: mysql:5.7
    container_name: splay_db
    environment:
      MYSQL_ROOT_PASSWORD: "splay"
      MYSQL_DATABASE: "splay"
      MYSQL_USER: "splay"
      MYSQL_PASSWORD: "splay"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 100
    ports: ["3306:3306"]
    expose:
      - "3306"

  # IMAGE : BACKEND JsonAPI  - also create the database/tables with active record
  backend:
    environment:
      - MASTER_KEY=devmasterkey
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: splay_backend
    ports: ["8081:3000"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /tmp/splaylogs/logs:/app/log/splay
      - ./src/backend/:/app
      - /app/tmp/

  # IMAGE : Controller - need waiting backend to create database (and table)
  controller:
    cpus: 2.0 # Reduce problemen when performance bug accured (see Trello)
    build:
      context: ./src/controller
    container_name: splay_controller
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - /tmp/splaylogs/logs:/usr/splay/logs

  # IMAGE : Daemon - splaydaemon
  daemon:
    cpus: 0.2 # Reduce problemen when performance bug accured (see Trello)
    build:
      context: ./src/daemon
    depends_on:
      controller:
        condition: service_started

  # IMAGE : Single page app to monitor splay. (use backend api service)
  web_app:
    #cpus: 0.5
    build:
      context: ./src/web_app
      dockerfile: dev.Dockerfile
    container_name: splay_web_app
    ports:
      - "8080:8080"
    depends_on: ["backend"]
    volumes:
      - "./src/web_app/:/app"

  # IMAGE : Command line interface using backed (tested purpose)
  cli:
    build:
      context: ./src/cli
    container_name: splay_cli
    depends_on: ["backend"]
    volumes:
      - "./src/cli/algorithms:/usr/splay/algorithms"